# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Subscription _ UST(1674f375-e996-4423-bd25-e0e8f6e76d13)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd infra
      terraform init
      terraform plan
      terraform apply --auto-approve
